includes:
- 'common.yaml'
deliverables:
- name: 'HTML5'
  context:
    idref: 'html'
  output: '.'
  publication:
    transtype: 'html5'
    params:
    - name: 'args.copycss'
      value: 'yes'
    - name: 'args.css'
      value: 'dita-ot-doc.css'
    - name: 'args.csspath'
      value: 'css'
    - name: 'args.cssroot'
      path: '../../resources'
    - name: 'args.gen.task.lbl'
      value: 'YES'
    - name: 'args.hdr'
      href: '../../resources/header.xml'
    - name: 'args.rellinks'
      value: 'noparent'
    - name: 'html5.toc.generate'
      value: 'no'
    - name: 'nav-toc'
      value: 'partial'
apps:
  ac-disc: 22.43.3
  as-admin: 2.13.43
  ar-user: 322.3.93

codes:
  ac-disc-code: AQWD
  as-admin-code: UYJI
  ar-user-code: MJNH
