uat:
  ac-disc: 2.4.1
  ac-disc-code: AVSA
  as-admin: 2.1.4
  as-admin-code: WESA
  ar-user: 3.8.9
  ar-user-code: QWXC
  ae-war: 12.78.90
  ae-war-code: QWXY
  data-ui: 13.78.08
  data-ui-code: QWXQ
