name: Run SQL Scripts and Collect Logs

on:
  workflow_dispatch:
    inputs:
      scripts_to_run:
        description: "Specify 'all' or comma-separated SQL script names (e.g., script1.sql,script2.sql)"
        required: true
        default: "all"

jobs:
  run-sql-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set SQL Scripts List
        id: set_scripts
        run: |
          if [ "${{ github.event.inputs.scripts_to_run }}" = "all" ]; then
            scripts="script1.sql script2.sql script3.sql script4.sql script5.sql script6.sql"
          else
            scripts=$(echo "${{ github.event.inputs.scripts_to_run }}" | tr ',' ' ')
          fi
          echo "scripts=$scripts" >> $GITHUB_OUTPUT

      - name: Create Logs Directory
        run: mkdir -p sql_logs

      - name: Execute SQL Scripts and Generate Logs
        run: |
          for script in ${{ steps.set_scripts.outputs.scripts }}; do
            echo "Running $script..."
            log_file="sql_logs/${script%.sql}.log"
            psql -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f ./db_scripts/$script > $log_file 2>&1
            echo "$script execution completed. Log saved to $log_file"
          done
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sql-execution-logs
          path: sql_logs/
