name: Parse Json

on:
  workflow_dispatch:

   inputs:
      value:
        description: 'input'
        required: false
        default: none

jobs:
  use-json-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Parse JSON variable
        run: |
          echo '${{ vars.MY_JSON_VARIABLE }}' | jq -r '.env'
          echo '${{ vars.MY_JSON_VARIABLE }}' | jq -r '.replicas'
          echo '${{ vars.MY_JSON_VARIABLE }}' | jq -r '.code'

          # Store GitHub variable JSON in a shell variable
          MY_JSON='${{ vars.MY_JSON_VARIABLE }}'

          # Get input key and trim spaces
          ip="$(echo '${{ github.event.inputs.value }}' | xargs)"

          echo "Looking up key: $ip"
          echo "$MY_JSON" | jq -r --arg key "$ip" '.[$key]'
