name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      application:
        required: true
      version:
        required: true
      environment:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying ${{ github.event.inputs.application }} version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"
